version: "3.9"
services:
  db:
    image: postgres:15
    container_name: prisma_demo_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: prisma_demo_db
    ports:
      - "5432:5432"
    volumes:
      - prisma_demo_db_data:/var/lib/postgresql/data

volumes:
  prisma_demo_db_data:
